  #Nginx Service
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/bc:/usr/share/nginx/html
      - /home/ubuntu/ssl:/ssl
      - /home/ubuntu/conf/:/etc/nginx/conf.d
